apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dataspace.name }}-public-portal-frontend
  labels:
    service: {{ .Values.dataspace.name }}-public-portal-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    service: {{ .Values.dataspace.name }}-public-portal-frontend
