apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dataspace.name }}-public-portal-backend
  labels:
    service: {{ .Values.dataspace.name }}-public-portal-backend
spec:
  ports:
    - name: http
      port: 1337
      targetPort: 1337
  selector:
    service: {{ .Values.dataspace.name }}-public-portal-backend