apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataspace.name }}-public-portal-backend-secret
  labels:
    service: {{ .Values.dataspace.name }}-public-portal-backend
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.services.db.portal.user | b64enc }}
  DATABASE_PASSWORD: "{{ .Values.services.db.portal.password | b64enc }}"
  JWT_SECRET: "{{ .Values.backend.jwt.secret.core | b64enc }}"
  ADMIN_JWT_SECRET: "{{ .Values.backend.jwt.secret.admin | b64enc }}"
  APP_KEYS: "{{ .Values.backend.app.keys | b64enc }}"
  API_TOKEN_SALT: "{{ .Values.backend.api.token.salt | b64enc }}"
  TOKEN_USERNAME: {{ .Values.backend.oauth2.username | b64enc }}
  TOKEN_PASSWORD: "{{ .Values.backend.oauth2.password | b64enc }}"
  