apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.connector.name }}-interface
  name: {{ .Values.connector.name }}-interface
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: {{ .Values.connector.name }}-interface
