apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-admin-tls-cert
  namespace: common-srvs
spec:
  secretName: keycloak-admin-tls-cert
  duration: 8760h
  renewBefore: 720h
  commonName: comsrvs-admin-keycloak
  dnsNames:
    - "*.comsrvs-keycloak"
    - "*.common-srvs.svc"
    - "*.ds.inesdata.upm"
    - admin.auth.ds.inesdata.upm
    - comsrvs-keycloak
    - keycloak
  issuerRef:
    name: elastic-selfsigned-cluster-issuer
    kind: ClusterIssuer
