name: inesdata-ds-common
description: Helm chart to deploy the base services for an inesdata dataspaces-deployment
version: 1.0.0
apiVersion: v2
dependencies:
  - name: postgresql
    version: "~15.5.38"
    repository: "oci://registry-1.docker.io/bitnamicharts"
