apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataspace.name }}-registration-service-secret
  labels:
    service: {{ .Values.dataspace.name }}-registration-service
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.services.db.registration.password | b64enc }}
  